// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZ7AGcevF4KSUjbphqPGlcRKzX5A6sSs',
    appId: '1:335141937323:web:6486e41a6bd1f012d657ee',
    messagingSenderId: '335141937323',
    projectId: 'fitdiva',
    authDomain: 'fitdiva.firebaseapp.com',
    storageBucket: 'fitdiva.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9kUnzYVnX8EIx70kr0gCHVAzompKDHXU',
    appId: '1:335141937323:android:aa4bac60418ccf66d657ee',
    messagingSenderId: '335141937323',
    projectId: 'fitdiva',
    storageBucket: 'fitdiva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosaiH8n-VV7U-9V7c3ZRgKkfWh1kCNgw',
    appId: '1:335141937323:ios:ebb004f5883fa248d657ee',
    messagingSenderId: '335141937323',
    projectId: 'fitdiva',
    storageBucket: 'fitdiva.firebasestorage.app',
    iosBundleId: 'com.example.fitdiva',
  );
}
